name: Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Install app dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate app imports
        run: |
          python -c "import main; print('✅ main.py imported successfully')"
