name: Web Build + Deployment to GitHub Pages 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.8
  FLET_CLI_VERSION: 0.27.5
  PYTHONUTF8: 1
  FLET_CLI_NO_RICH_OUTPUT: 1
  UV_NO_PROGRESS: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'        # or whichever Flutter version you target

      - name: Install flet-cli
        run: |
          python -m pip install --upgrade pip
          pip install flet-cli==${{ env.FLET_CLI_VERSION }}

      - name: Flet Build Web
        run: |
          echo "Building web with base URL '/${{ github.repository#*/ }}/'"
          flet build web \
            --base-url "/${{ github.repository#*/ }}/" \
            --route-url-strategy hash

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: web-build-artifact
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      actions: read

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web-build-artifact
